extract_tasks:
  - name: extract_task1
    source: pg
    query: "SELECT * FROM table_name"
    tag: 
    interval: 10
  - name: extract_task2
    source: pg
    query: "SELECT * FROM another_table"
    tag:
    interval: 5

load_tasks:
  - name: load_task1
    destination: pi
    tag: tag_name
    interval: 10
  - name: load_task2
    destination: pi
    tag: another_tag
    interval: 5

